version: "3.7"

services:
  n8n:
    build: .
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=changeme-super-secret-key
      - N8N_PORT=5678
      - N8N_HOST=0.0.0.0
      - N8N_EDITOR_BASE_URL=https://a.w-partners.org/
      - WEBHOOK_TUNNEL_URL=https://a.w-partners.org/
      - EXECUTIONS_PROCESS=queue
      - QUEUE_MODE=true
      - QUEUE_CONCURRENCY=6
      - GENERIC_TIMEZONE=Asia/Seoul
      - NODE_ENV=production
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secure_password_123
    volumes:
      - ~/.n8n:/home/node/.n8n
    depends_on:
      - redis

  redis:
    image: redis:6
    ports:
      - "6379:6379"
