version: "3.7"
services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=changeme-super-secret-key
      - N8N_PORT=5678
      - EXECUTIONS_PROCESS=queue
      - QUEUE_MODE=true
      - QUEUE_CONCURRENCY=5
    volumes:
      - ~/.n8n:/home/node/.n8n
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
